"""empty message

Revision ID: 1a6f98856925
Revises: None
Create Date: 2015-04-03 22:58:42.563705

"""

# revision identifiers, used by Alembic.
revision = '1a6f98856925'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rank',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rank_rank'), 'rank', ['rank'], unique=True)
    op.create_table('user_old',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_old_email'), 'user_old', ['email'], unique=True)
    op.create_index(op.f('ix_user_old_nickname'), 'user_old', ['nickname'], unique=True)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('password', sa.String(length=10), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('registered_on', sa.DateTime(), nullable=True),
    sa.Column('rank_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rank_id'], ['rank.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_old_nickname'), table_name='user_old')
    op.drop_index(op.f('ix_user_old_email'), table_name='user_old')
    op.drop_table('user_old')
    op.drop_index(op.f('ix_rank_rank'), table_name='rank')
    op.drop_table('rank')
    ### end Alembic commands ###
